# Generated by Django 2.1.2 on 2018-11-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180920_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='client', max_length=20),
        ),
    ]
