# Generated by Django 2.1.2 on 2018-11-03 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_quiz_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='users_appeared',
            field=models.ManyToManyField(blank=True, related_name='users_appeared', to=settings.AUTH_USER_MODEL),
        ),
    ]
