# Generated by Django 2.1.3 on 2019-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190113_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
